### ISSUE TITLE
headings not captured

### ISSUE THREAD

**Issue by nylki** [leipert/language-pfm#1]
When switching from gfm to pfm headings are not recognized and the scope logs:
`source-gfm` instead of `source.pfm
markup.heading.heading-2.pfm` or similiar.

Others like _emphasis_ and **bold** work, however.

gfm:
![bildschirmfoto von 2015-03-14 11 52 58](https://cloud.githubusercontent.com/assets/1710598/6651392/ba80787e-ca40-11e4-86a7-3a937b534431.png)

pfm:
![bildschirmfoto von 2015-03-14 11 53 09](https://cloud.githubusercontent.com/assets/1710598/6651394/bb5cdb8e-ca40-11e4-8bc5-80877ec3af1d.png)

**Comment by leipert** [comment]
Yes, I fixed it in release 0.68.0
Also I added a CI-Badge from wercker to the README, so you are able to see if everything works :)

Added an own math mode instead of relying on language-latex:

![screen shot 2015-03-14 at 15 36 12](https://cloud.githubusercontent.com/assets/2906107/6652065/f9d4048a-ca60-11e4-8c3f-c490c68b6559.png)
